// The node configuration: the only input the control plane gives the dataplane.
//
// This file is the contract between the Go control plane and the Rust dataplane and
// generates both, so neither side hand-writes these types.
//
// Delivery. The control plane rename(2)s a complete new file into the watched directory;
// the node watches the directory, not the file. Every push is the whole configuration,
// never a patch. A new file is validated in full, then against the config already running;
// either failure rejects the whole file and the node keeps what it has. The only signal is
// the rejected-configs counter in the node's metrics, so watch it.
//
// Zero is reserved. No node, zone, universe, extent or device id may be zero, so zero
// always means "none": `Extent.next_zone = 0` is "not migrating" and nothing else.
//
// The model. A *universe* is a flat, sparse address space in 4 KiB units spanning a set of
// nodes, and at once the transport reaching them, the security boundary around them and the
// consensus domain they agree in. An *extent* is a contiguous run of that space with one
// page size, kind, home zone and tombstone epoch: the unit of placement, sealing, migration
// and accounting. A *device* is a local block device this node exports, composed of whole
// extents in any order; two nodes may compose different devices from the same extents, and
// a node may hold extents no device exports.
//
// Reloads. `Node.store` is read at format time or startup, so changing it does nothing
// until the process restarts. An existing extent's `base_lba`, `pages` and `kind` are
// frozen for its life, as is an existing device's extent list. Every other field is hot.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: config.proto

package racerconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cohort int32

const (
	Cohort_COHORT_0 Cohort = 0
	Cohort_COHORT_1 Cohort = 1
	Cohort_COHORT_2 Cohort = 2
)

// Enum value maps for Cohort.
var (
	Cohort_name = map[int32]string{
		0: "COHORT_0",
		1: "COHORT_1",
		2: "COHORT_2",
	}
	Cohort_value = map[string]int32{
		"COHORT_0": 0,
		"COHORT_1": 1,
		"COHORT_2": 2,
	}
)

func (x Cohort) Enum() *Cohort {
	p := new(Cohort)
	*p = x
	return p
}

func (x Cohort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Cohort) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[0].Descriptor()
}

func (Cohort) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[0]
}

func (x Cohort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Cohort.Descriptor instead.
func (Cohort) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

type Kind int32

const (
	// Last writer wins: the guard is the page's current version, so a write always lands.
	Kind_LWW Kind = 0
	// Optimistic concurrency: the guard is the version *this node* last read, so a write with
	// no prior read here conflicts. Acceptors keep no read state, which makes the check
	// cluster-wide rather than per-replica.
	Kind_OCC Kind = 1
	// Write-once per tombstone epoch, in 4 KiB pages: the guard is
	// `3 * Extent.tombstone_epoch`, which every replica derives from this file identically.
	// The only guard needing no bits on the wire.
	Kind_IMMUTABLE Kind = 2
	// The same guard, in 4 MiB pages. The only kind at that size, and why a derived guard
	// matters: a 4 MiB frame is all payload, with no room to carry one on the wire.
	Kind_IMMUTABLE_4M Kind = 3
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "LWW",
		1: "OCC",
		2: "IMMUTABLE",
		3: "IMMUTABLE_4M",
	}
	Kind_value = map[string]int32{
		"LWW":          0,
		"OCC":          1,
		"IMMUTABLE":    2,
		"IMMUTABLE_4M": 3,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_config_proto_enumTypes[1].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_config_proto_enumTypes[1]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

type NodeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Strictly increasing per node; a value at or below the running one is rejected. Echoed
	// in the node's PING so a peer that redirected us on a stale topology can tell whether we
	// have the file yet. Opaque, and never compared across nodes.
	Generation uint64 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Node       *Node  `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	// The universes this node participates in. Each costs a ublk device and an exported
	// namespace, as does each device below; together they are capped by the node's device
	// budget (256).
	Universes []*Universe `protobuf:"bytes,3,rep,name=universes,proto3" json:"universes,omitempty"`
	// The block devices this node exports. Adding and removing devices is free; an existing
	// device's extent list is frozen (see Device).
	Devices []*Device `protobuf:"bytes,4,rep,name=devices,proto3" json:"devices,omitempty"`
	// Optional; absent means every default below.
	Policy        *Policy `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *NodeConfig) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *NodeConfig) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeConfig) GetUniverses() []*Universe {
	if x != nil {
		return x.Universes
	}
	return nil
}

func (x *NodeConfig) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *NodeConfig) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NodeId, non-zero. This node's identity to its peers, and the value matched against a
	// catalog group to find our position in it. One identity across every universe.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The fault domain, ~300 nodes. Each universe's `catalog` describes this zone only, and
	// this zone must not also appear in that universe's `zones`.
	Zone uint32 `protobuf:"varint,2,opt,name=zone,proto3" json:"zone,omitempty"`
	// The column of every catalog group that is our cooperative-cache roster: cohort `c`
	// takes column `c` of the whole catalog, which is why member order in a group is
	// normative. One column across every universe. Required, so that forgetting the field
	// cannot silently ship cohort 0.
	Cohort *Cohort `protobuf:"varint,3,opt,name=cohort,proto3,enum=racer.config.Cohort,oneof" json:"cohort,omitempty"`
	// The local backing store this node owns outright. One store behind every universe:
	// partitioning is enforced by what this node is admitted to, not by separate files.
	Store         *Store `protobuf:"bytes,4,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetZone() uint32 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *Node) GetCohort() Cohort {
	if x != nil && x.Cohort != nil {
		return *x.Cohort
	}
	return Cohort_COHORT_0
}

func (x *Node) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

// The local backing store this node owns outright: one regular file of exactly the length
// named here. Nothing here is on an IO path; every field goes into the superblock at format
// time, is read once at startup, or is checked at validation, so a change takes effect on
// the next restart. The path is deliberately absent, since where the file lives is a
// property of the deployment rather than of the cluster: it comes from the `RACER_STORE`
// environment variable (default /var/lib/racer/store.img).
type Store struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The length the backing file is held at, in bytes. Non-zero and a multiple of 4096.
	// Created at this length on first start and extended to it later, so raising this and
	// restarting is how a node gains capacity. It may never be lowered: a config asking for
	// less than the file already has is rejected, as is a start that finds a longer file,
	// because the store is addressed by absolute offset and nothing could move its contents.
	//
	// Everything comes out of this: superblocks, the metadata region, and the data slabs
	// sized from every universe's extents. A configuration that does not fit is refused at
	// startup, naming this field. Whatever is left over is the read cache, with nothing to
	// configure: every 4 MiB the slabs did not claim goes to the cache, which gives it back
	// if a later config grows the slabs into it. `policy.cache_index_bytes` bounds the DRAM
	// that cache costs.
	SizeBytes uint64 `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// The rate this node will drive its own storage at. Set these below what the device under
	// the file will actually take, not at it: pacing our own submissions costs a bounded
	// wait, while overshooting storage that then delays or fails the excess costs an
	// unbounded one applied to whichever IO is in flight.
	//
	// Both are enforced at once and either can bind first: small writes exhaust operations
	// while the byte budget idles, and a 4 MiB page does the reverse. A transfer larger than
	// 256 KiB is charged as several operations. Zero leaves that resource unmetered. When the
	// budget is committed far enough ahead, cache admission and anti-entropy stand down so
	// guest IO and consensus keep the rest.
	MaxIops        uint64 `protobuf:"varint,2,opt,name=max_iops,json=maxIops,proto3" json:"max_iops,omitempty"`
	MaxBytesPerSec uint64 `protobuf:"varint,3,opt,name=max_bytes_per_sec,json=maxBytesPerSec,proto3" json:"max_bytes_per_sec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *Store) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Store) GetMaxIops() uint64 {
	if x != nil {
		return x.MaxIops
	}
	return 0
}

func (x *Store) GetMaxBytesPerSec() uint64 {
	if x != nil {
		return x.MaxBytesPerSec
	}
	return 0
}

// A universe: one flat address space, one transport, one security boundary, one consensus
// domain. Universes share this node's store, cores and cache and nothing else; each has its
// own topology epoch, catalog, peer zones and links, and no address, group, seal or
// migration crosses between them.
//
// The dataplane exports one ublk device per universe and the control plane publishes it as
// a namespace to that universe's members alone. A frame's universe is not a field on the
// wire, it is which namespace the frame arrived on, so the transport enforces partitioning
// rather than a check the dataplane could get wrong.
type Universe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique, never reused, non-zero, below 2^26. It is the high 26 bits of every
	// address here: an address is `universe:26 | lba:38`, so a universe spans 2^38 4 KiB
	// blocks, or 1 PiB. Zero is reserved because a zero address means "free" on device.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Bumped by the control plane whenever this universe's topology changes. It rides in the
	// trailer of every routed write and is the term used when an extent is sealed, which is
	// persisted. Treat it as monotonic: nothing enforces that, and a decrease silently walks
	// seal terms backwards.
	Epoch uint32 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// The consensus groups of this zone within this universe; an entry's index is its group
	// index. Each is three distinct, non-zero nodes. ~300 entries.
	//
	// An address hashes to one of 16384 slots, and the slot rather than the group travels on
	// the wire; the owning group is `slot % len(catalog)`. The length is therefore fixed for
	// the life of the zone and a reload that changes it is refused: the group also selects
	// the core that serves the address and the key anti-entropy accumulates digests under,
	// and nothing moves pages between groups. Ownership moves by changing a group's members.
	//
	// The catalog must be balanced, because the nodes of a zone are homogeneous: every node
	// it names appears in exactly `3 * len(catalog) / n` groups, where `n` is the number of
	// distinct nodes named, and `n` must divide `3 * len(catalog)`. An unbalanced catalog is
	// refused. This is the only capacity model: a node sizes its store from that equal share
	// in each universe it joins, so every node of a zone formats identically.
	//
	// Consecutive generations may differ by at most one member id. The newcomer inherits the
	// departing node's groups and replays them from its peers; the departing node drops what
	// it held once the new members confirm they have it. A node that has missed generations
	// is held to no such step, since it is handed a settled state rather than a transient.
	//
	// A node this catalog does not name is not a member of this zone in this universe: it is
	// either draining under the config that dropped it, or it only routes for others.
	Catalog []*Trio `protobuf:"bytes,3,rep,name=catalog,proto3" json:"catalog,omitempty"`
	// The other zones of this universe, with their gateway nodes. Exactly the set an extent's
	// `zone`, `next_zone` and `warm_zones` may name besides our own, which keeps this message
	// O(zones) rather than O(cluster). Must not list our own zone; ids must be unique.
	Zones []*Zone `protobuf:"bytes,4,rep,name=zones,proto3" json:"zones,omitempty"`
	// One NVMe link per entry, each to this universe's namespace on the named node. A peer
	// reached in two universes appears once in each with a different path, and the two links
	// are unrelated: a frame is answered in the universe it arrived on. Fully hot: an
	// unchanged device path keeps its open fd across a reload, and a dropped peer is torn
	// down only after the previous generation retires.
	//
	// A universe with no peers is its own quorum of one: deliberate isolation, not a degraded
	// mode. Do not ship an empty peer list for a universe meant to be replicated.
	Peers []*Peer `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	// The extents of this universe this node has been told about, sorted by `base_lba` and
	// non-overlapping. This is the control plane's map of the address space and what makes an
	// address meaningful: an address outside every extent is unmapped and every operation on
	// it is refused. A node is told about the extents it stores, exports or routes for, and
	// need not be told about the rest of the universe.
	Extents []*Extent `protobuf:"bytes,6,rep,name=extents,proto3" json:"extents,omitempty"`
	// The ublk minor this node exports this universe's fabric namespace on, so the path is
	// `/dev/ublkb<fabric_device_id>` and the control plane knows it before the node starts.
	// Non-zero, unique on this node against every other universe's value and every
	// `Device.id`, and counted against the same 256 export budget. The control plane
	// publishes this device as an NVMe-oF namespace to exactly this universe's members, and
	// the paths it hands back are the `Peer.device` entries they open. Frozen for the life of
	// the universe here: changing it moves every peer's path and drops every open fd.
	FabricDeviceId uint32 `protobuf:"varint,7,opt,name=fabric_device_id,json=fabricDeviceId,proto3" json:"fabric_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Universe) Reset() {
	*x = Universe{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Universe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Universe) ProtoMessage() {}

func (x *Universe) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Universe.ProtoReflect.Descriptor instead.
func (*Universe) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *Universe) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Universe) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Universe) GetCatalog() []*Trio {
	if x != nil {
		return x.Catalog
	}
	return nil
}

func (x *Universe) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *Universe) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *Universe) GetExtents() []*Extent {
	if x != nil {
		return x.Extents
	}
	return nil
}

func (x *Universe) GetFabricDeviceId() uint32 {
	if x != nil {
		return x.FabricDeviceId
	}
	return 0
}

// One end of a fabric link, within one universe. No address, port or NQN here on purpose:
// connecting is the control plane's job, and by the time the dataplane sees this the link
// is just a local file to open.
type Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The remote node's id. Non-zero, not our own, unique within this universe's peer list.
	// This is what turns a catalog group member into a link.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Local path to this peer's namespace *for this universe*, already attached by the
	// control plane. Two universes reaching the same node name two different paths.
	Device        string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *Peer) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

// Three node ids in cohort order. Position is normative: in a catalog group it is the paxos
// member index, with quorum 2 of 3, and the column is the cooperative-cache cohort.
type Trio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cohort_0      uint32                 `protobuf:"varint,1,opt,name=cohort_0,json=cohort0,proto3" json:"cohort_0,omitempty"`
	Cohort_1      uint32                 `protobuf:"varint,2,opt,name=cohort_1,json=cohort1,proto3" json:"cohort_1,omitempty"`
	Cohort_2      uint32                 `protobuf:"varint,3,opt,name=cohort_2,json=cohort2,proto3" json:"cohort_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trio) Reset() {
	*x = Trio{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trio) ProtoMessage() {}

func (x *Trio) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trio.ProtoReflect.Descriptor instead.
func (*Trio) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *Trio) GetCohort_0() uint32 {
	if x != nil {
		return x.Cohort_0
	}
	return 0
}

func (x *Trio) GetCohort_1() uint32 {
	if x != nil {
		return x.Cohort_1
	}
	return 0
}

func (x *Trio) GetCohort_2() uint32 {
	if x != nil {
		return x.Cohort_2
	}
	return 0
}

// A peer zone of this universe, and the nodes of it that accept traffic from outside.
//
// A sender ranks the gateways by rendezvous hash on the address and takes the highest it
// holds a link to, so load spreads over the whole set without negotiating and a gateway
// that is gone is skipped rather than fatal. Widen the set to spread cross-zone traffic
// over more of the zone's edge; size it so losing one node still leaves a reachable
// gateway. Unlike the cooperative cache's ring this one promotes, handing a skipped
// gateway's share to the next, because any gateway can resolve any address in its zone and
// no counterparty has to agree on the choice.
type Zone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Non-empty, non-zero, unique, and not this node. At most 64. At least one must also
	// appear in this universe's `peers`: a zone we hold no link into is a zone we cannot
	// route to, and a config naming an unreachable zone is refused up front.
	Gateways      []uint32 `protobuf:"varint,2,rep,packed,name=gateways,proto3" json:"gateways,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *Zone) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Zone) GetGateways() []uint32 {
	if x != nil {
		return x.Gateways
	}
	return nil
}

type Extent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Non-zero, and unique across every universe in this file, not merely within its own: the
	// dataplane keys seals, the census and the per-extent metrics by this id alone, and a
	// device names its extents by it. Allocate extent ids from one space. Never reused.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Where this extent starts in its universe's address space, in 4 KiB blocks. Frozen for
	// the extent's life, since a page's address is `universe | base_lba + offset` and nothing
	// could move stored pages. The control plane places extents; the dataplane never picks a
	// base. For an IMMUTABLE_4M extent this must be a multiple of 1024, since each of its
	// pages spans 1024 blocks. `base_lba` plus the extent's span must fit in 2^38.
	BaseLba uint64 `protobuf:"varint,2,opt,name=base_lba,json=baseLba,proto3" json:"base_lba,omitempty"`
	// Length in *pages* of this extent's kind, not in blocks and not in bytes, so a
	// misaligned extent is unrepresentable. Non-zero. Summed across every universe this sizes
	// the store at format time and is what the index budget is checked against, so it cannot
	// change once the extent exists. Grow capacity by adding an extent, not by extending one.
	Pages uint64 `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	// Frozen for the extent's life. Sets the guard a write must present and the page size,
	// and nothing else; the kinds share one code path.
	Kind Kind `protobuf:"varint,4,opt,name=kind,proto3,enum=racer.config.Kind" json:"kind,omitempty"`
	// Home zone: where these bytes live. Must be our own zone or one listed in this
	// universe's `zones`.
	Zone uint32 `protobuf:"varint,5,opt,name=zone,proto3" json:"zone,omitempty"`
	// 0 = not migrating; else the zone the bytes are being pulled to. Must differ from `zone`
	// and be a zone this universe knows. Setting it starts a migration: the source zone seals
	// the extent and pushes it, and the destination treats incoming writes for it as local.
	// It keeps pushing until the control plane sets `zone` to this value and clears this
	// field to 0. That flip is the only completion signal there is; the dataplane never
	// decides a migration has finished, and a home zone may only move to the value
	// `next_zone` previously held. Nothing moves an extent between universes.
	NextZone uint32 `protobuf:"varint,6,opt,name=next_zone,json=nextZone,proto3" json:"next_zone,omitempty"`
	// The most load-bearing scalar in this file, scoped to this extent alone. Page versions
	// in it are `3*epoch + state`: `3e` empty, `3e+1` live, `3e+2` trimmed. Advancing it does
	// three things at once with no consensus round: the extent's tombstones from every
	// earlier epoch become reclaimable, every cached immutable page in it is invalidated, and
	// the guard an immutable write must present moves to `3*epoch`. Other extents are
	// untouched.
	//
	// It may never decrease, which would put the fill point below entries the extent already
	// holds and make every later write to them conflict forever. Any forward step is legal,
	// so a node down for several generations adopts the current value rather than refusing
	// the whole file.
	//
	// Advancing is destructive, not just a collection: every page still live below the new
	// epoch becomes unreadable and its slot is never reclaimed. Advance only once every node
	// reports `racer_extent_live_pages{extent=...} == 0` at the current epoch; afterwards
	// `racer_extent_tombstones{extent=...}` draining to zero is the sweep finishing.
	TombstoneEpoch uint32 `protobuf:"varint,7,opt,name=tombstone_epoch,json=tombstoneEpoch,proto3" json:"tombstone_epoch,omitempty"`
	// Cache admission for this extent, and the only knob deciding whether a page of it may
	// enter a node's cache at all:
	//
	//	0       never; pages of this extent are not cached, and are not even counted
	//	1       admit on first sight
	//	2..=15  admit once the frequency estimate reaches this value
	//
	// The estimate is requests per 250 ms decay interval, not an IOPS rate, and it saturates
	// at 15, so larger values are strictly stricter. Use 1 for a working set that fits and is
	// read repeatedly, 2 or 3 where one-hit wonders would churn the cache, and 0 for an
	// extent scanned once, such as a backup source.
	//
	// It is an admission threshold and nothing more: it reserves no capacity and does not
	// rank extents. Once admitted, a page competes for slots purely on measured frequency, so
	// a hot page of one extent displaces a cold page of another whatever their thresholds
	// were. Raising it evicts nothing already resident. Changing it is legal on any reload,
	// and dropping to 0 stops admission immediately.
	CacheAdmit uint32 `protobuf:"varint,8,opt,name=cache_admit,json=cacheAdmit,proto3" json:"cache_admit,omitempty"`
	// Zones whose caches are filled with pages of this extent as they are committed, rather
	// than on first demand. Read symmetrically: a node in the home `zone` pushes toward every
	// zone named here, and a node whose own zone is named is a warm destination. Each must be
	// a zone this universe knows, and none may be `zone` or `next_zone`. At most 16. Use it
	// for pages another zone will certainly read soon after they are written; the cooperative
	// cache is otherwise demand-filled, so its first read of a key is always a miss, and
	// warming pays that miss out of the writer's latency budget rather than the reader's.
	//
	// Only an IMMUTABLE or IMMUTABLE_4M extent may name zones here; anything else is refused.
	// A warmed page is served locally with no confirmation round, which would cost the fabric
	// crossing warming exists to avoid, and only an immutable page can be believed on sight:
	// its version is a function of `tombstone_epoch`, so a copy either carries the live
	// version or is recognisably not the value, and one epoch bump invalidates every zone's
	// copies at once. A mutable page has no such self-check, and a remote reader trusting one
	// would serve bytes its group had already replaced.
	//
	// Advisory in every direction: a push may be dropped at the source under pressure, lost
	// on the wire, or declined at the destination, and nothing observes whether it arrived. A
	// destination that was not warmed simply reads across the WAN.
	//
	// `cache_admit` still governs the destination: 0 vetoes warming, and a threshold of
	// `2..=15` is *bypassed*, since it measures demand and a page just warmed has none yet.
	// Costs one page transfer per cohort per named zone on every commit, so three WAN
	// transfers per zone, paid whether or not anyone there ever reads the page.
	WarmZones     []uint32 `protobuf:"varint,9,rep,packed,name=warm_zones,json=warmZones,proto3" json:"warm_zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extent) Reset() {
	*x = Extent{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extent) ProtoMessage() {}

func (x *Extent) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extent.ProtoReflect.Descriptor instead.
func (*Extent) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *Extent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Extent) GetBaseLba() uint64 {
	if x != nil {
		return x.BaseLba
	}
	return 0
}

func (x *Extent) GetPages() uint64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *Extent) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_LWW
}

func (x *Extent) GetZone() uint32 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *Extent) GetNextZone() uint32 {
	if x != nil {
		return x.NextZone
	}
	return 0
}

func (x *Extent) GetTombstoneEpoch() uint32 {
	if x != nil {
		return x.TombstoneEpoch
	}
	return 0
}

func (x *Extent) GetCacheAdmit() uint32 {
	if x != nil {
		return x.CacheAdmit
	}
	return 0
}

func (x *Extent) GetWarmZones() []uint32 {
	if x != nil {
		return x.WarmZones
	}
	return nil
}

// A block device this node exports, assembled from whole extents.
//
// The device is the concatenation of `extents` in the order given: extent N's pages begin
// where N-1's ended. Nothing here is stored, since a device is a view; the same extent may
// appear in devices on several nodes, in different positions, alongside different
// neighbours. A device may not name the same extent twice, which would alias two offsets
// onto one page, and every extent in it must have the same page size, since the exported
// device advertises one page as both its maximum transfer and its chunk size.
type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Non-zero and unique in this file. Names the exported ublk device for its life; a device
	// that keeps its id and its extent list across a reload keeps its open handles.
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Extent ids, in the order they are concatenated. Non-empty, no duplicates, and every id
	// must name an extent of some universe in this file. Extents from different universes may
	// share a device: composing is a local act, and the boundary is about who may address a
	// universe, not about which of a node's own devices its bytes appear in.
	//
	// Frozen for the device's life: a guest that has the device open is addressing positions
	// in it, and reordering or resizing under it would silently redirect every offset past
	// the change. Publish a new device id instead.
	Extents       []uint32 `protobuf:"varint,2,rep,packed,name=extents,proto3" json:"extents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *Device) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Device) GetExtents() []uint32 {
	if x != nil {
		return x.Extents
	}
	return nil
}

type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DRAM ceiling for the 4 KiB index, in bytes. Checked once when a config is loaded: the
	// total 4 KiB page count times 52 B must fit, or the config is refused by name rather
	// than allowed to OOM later. 4 MiB pages are not counted. Absent means the default, 8
	// GiB. An admission check only, so nothing enforces it at runtime.
	MaxIndexBytes *uint64 `protobuf:"varint,1,opt,name=max_index_bytes,json=maxIndexBytes,proto3,oneof" json:"max_index_bytes,omitempty"`
	// DRAM ceiling for the OCC read pool, in bytes. Split evenly across cores at 48 B per
	// record, minimum one record per core. Absent means the default, 256 MiB. Genuinely hot:
	// shrinking it evicts on the next tick. Too small only turns would-be successful OCC
	// writes into conflicts the client retries, never a wrong answer.
	OccBytes *uint64 `protobuf:"varint,2,opt,name=occ_bytes,json=occBytes,proto3,oneof" json:"occ_bytes,omitempty"`
	// Registers one anti-entropy sweep will pull while replaying a group, and the number it
	// will push per extent while handing one to another zone. Absent means the default, 4096.
	// Zero is refused.
	//
	// This is the rate a member replacement runs at. A group being replayed is running two of
	// three with no fault tolerance left, so the window wants to be short; against that,
	// every register costs a prepare round at the whole group and the members sourcing it are
	// serving clients. Raise it to finish faster on a cluster with headroom, lower it to keep
	// replacement out of the way of the write path.
	RepairsPerReplay *uint32 `protobuf:"varint,4,opt,name=repairs_per_replay,json=repairsPerReplay,proto3,oneof" json:"repairs_per_replay,omitempty"`
	// DRAM ceiling for the read cache's index, in bytes, across every core and both page
	// classes. Absent means the default, 1 GiB; zero disables the cache by leaving it no
	// slots to hold.
	//
	// This is what bounds the cache, because the media no longer does: the cache is given
	// every 4 MiB the slabs did not claim, which on a large store is more space than any sane
	// amount of DRAM can index. One resident page costs 48 B here, so a 4 MiB chunk costs
	// 48 B as one huge page and 48 KiB as 1024 small ones; the small class is 1024 times more
	// expensive per byte of media. Unlike max_index_bytes this is not an admission check: the
	// cache sizes itself to fit and simply holds less.
	CacheIndexBytes *uint64 `protobuf:"varint,5,opt,name=cache_index_bytes,json=cacheIndexBytes,proto3,oneof" json:"cache_index_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *Policy) GetMaxIndexBytes() uint64 {
	if x != nil && x.MaxIndexBytes != nil {
		return *x.MaxIndexBytes
	}
	return 0
}

func (x *Policy) GetOccBytes() uint64 {
	if x != nil && x.OccBytes != nil {
		return *x.OccBytes
	}
	return 0
}

func (x *Policy) GetRepairsPerReplay() uint32 {
	if x != nil && x.RepairsPerReplay != nil {
		return *x.RepairsPerReplay
	}
	return 0
}

func (x *Policy) GetCacheIndexBytes() uint64 {
	if x != nil && x.CacheIndexBytes != nil {
		return *x.CacheIndexBytes
	}
	return 0
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\fracer.config\"\xe8\x01\n" +
	"\n" +
	"NodeConfig\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12&\n" +
	"\x04node\x18\x02 \x01(\v2\x12.racer.config.NodeR\x04node\x124\n" +
	"\tuniverses\x18\x03 \x03(\v2\x16.racer.config.UniverseR\tuniverses\x12.\n" +
	"\adevices\x18\x04 \x03(\v2\x14.racer.config.DeviceR\adevices\x12,\n" +
	"\x06policy\x18\x05 \x01(\v2\x14.racer.config.PolicyR\x06policy\"\x93\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\rR\x04zone\x121\n" +
	"\x06cohort\x18\x03 \x01(\x0e2\x14.racer.config.CohortH\x00R\x06cohort\x88\x01\x01\x12)\n" +
	"\x05store\x18\x04 \x01(\v2\x13.racer.config.StoreR\x05storeB\t\n" +
	"\a_cohort\"l\n" +
	"\x05Store\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x04R\tsizeBytes\x12\x19\n" +
	"\bmax_iops\x18\x02 \x01(\x04R\amaxIops\x12)\n" +
	"\x11max_bytes_per_sec\x18\x03 \x01(\x04R\x0emaxBytesPerSec\"\x8c\x02\n" +
	"\bUniverse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\x12,\n" +
	"\acatalog\x18\x03 \x03(\v2\x12.racer.config.TrioR\acatalog\x12(\n" +
	"\x05zones\x18\x04 \x03(\v2\x12.racer.config.ZoneR\x05zones\x12(\n" +
	"\x05peers\x18\x05 \x03(\v2\x12.racer.config.PeerR\x05peers\x12.\n" +
	"\aextents\x18\x06 \x03(\v2\x14.racer.config.ExtentR\aextents\x12(\n" +
	"\x10fabric_device_id\x18\a \x01(\rR\x0efabricDeviceId\".\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\"W\n" +
	"\x04Trio\x12\x19\n" +
	"\bcohort_0\x18\x01 \x01(\rR\acohort0\x12\x19\n" +
	"\bcohort_1\x18\x02 \x01(\rR\acohort1\x12\x19\n" +
	"\bcohort_2\x18\x03 \x01(\rR\acohort2\"2\n" +
	"\x04Zone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bgateways\x18\x02 \x03(\rR\bgateways\"\x8b\x02\n" +
	"\x06Extent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\bbase_lba\x18\x02 \x01(\x04R\abaseLba\x12\x14\n" +
	"\x05pages\x18\x03 \x01(\x04R\x05pages\x12&\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x12.racer.config.KindR\x04kind\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\rR\x04zone\x12\x1b\n" +
	"\tnext_zone\x18\x06 \x01(\rR\bnextZone\x12'\n" +
	"\x0ftombstone_epoch\x18\a \x01(\rR\x0etombstoneEpoch\x12\x1f\n" +
	"\vcache_admit\x18\b \x01(\rR\n" +
	"cacheAdmit\x12\x1d\n" +
	"\n" +
	"warm_zones\x18\t \x03(\rR\twarmZones\"2\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\aextents\x18\x02 \x03(\rR\aextents\"\x8a\x02\n" +
	"\x06Policy\x12+\n" +
	"\x0fmax_index_bytes\x18\x01 \x01(\x04H\x00R\rmaxIndexBytes\x88\x01\x01\x12 \n" +
	"\tocc_bytes\x18\x02 \x01(\x04H\x01R\boccBytes\x88\x01\x01\x121\n" +
	"\x12repairs_per_replay\x18\x04 \x01(\rH\x02R\x10repairsPerReplay\x88\x01\x01\x12/\n" +
	"\x11cache_index_bytes\x18\x05 \x01(\x04H\x03R\x0fcacheIndexBytes\x88\x01\x01B\x12\n" +
	"\x10_max_index_bytesB\f\n" +
	"\n" +
	"_occ_bytesB\x15\n" +
	"\x13_repairs_per_replayB\x14\n" +
	"\x12_cache_index_bytes*2\n" +
	"\x06Cohort\x12\f\n" +
	"\bCOHORT_0\x10\x00\x12\f\n" +
	"\bCOHORT_1\x10\x01\x12\f\n" +
	"\bCOHORT_2\x10\x02*9\n" +
	"\x04Kind\x12\a\n" +
	"\x03LWW\x10\x00\x12\a\n" +
	"\x03OCC\x10\x01\x12\r\n" +
	"\tIMMUTABLE\x10\x02\x12\x10\n" +
	"\fIMMUTABLE_4M\x10\x03B2Z0github.com/Azure/unbounded/api/racer;racerconfigb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_config_proto_goTypes = []any{
	(Cohort)(0),        // 0: racer.config.Cohort
	(Kind)(0),          // 1: racer.config.Kind
	(*NodeConfig)(nil), // 2: racer.config.NodeConfig
	(*Node)(nil),       // 3: racer.config.Node
	(*Store)(nil),      // 4: racer.config.Store
	(*Universe)(nil),   // 5: racer.config.Universe
	(*Peer)(nil),       // 6: racer.config.Peer
	(*Trio)(nil),       // 7: racer.config.Trio
	(*Zone)(nil),       // 8: racer.config.Zone
	(*Extent)(nil),     // 9: racer.config.Extent
	(*Device)(nil),     // 10: racer.config.Device
	(*Policy)(nil),     // 11: racer.config.Policy
}
var file_config_proto_depIdxs = []int32{
	3,  // 0: racer.config.NodeConfig.node:type_name -> racer.config.Node
	5,  // 1: racer.config.NodeConfig.universes:type_name -> racer.config.Universe
	10, // 2: racer.config.NodeConfig.devices:type_name -> racer.config.Device
	11, // 3: racer.config.NodeConfig.policy:type_name -> racer.config.Policy
	0,  // 4: racer.config.Node.cohort:type_name -> racer.config.Cohort
	4,  // 5: racer.config.Node.store:type_name -> racer.config.Store
	7,  // 6: racer.config.Universe.catalog:type_name -> racer.config.Trio
	8,  // 7: racer.config.Universe.zones:type_name -> racer.config.Zone
	6,  // 8: racer.config.Universe.peers:type_name -> racer.config.Peer
	9,  // 9: racer.config.Universe.extents:type_name -> racer.config.Extent
	1,  // 10: racer.config.Extent.kind:type_name -> racer.config.Kind
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	file_config_proto_msgTypes[1].OneofWrappers = []any{}
	file_config_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		EnumInfos:         file_config_proto_enumTypes,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
