//go:build !ignore_autogenerated

// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha3

import (
	"github.com/Azure/unbounded/api/net/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentDownloadsSpec) DeepCopyInto(out *AgentDownloadsSpec) {
	*out = *in
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(DownloadSource)
		**out = **in
	}
	if in.Containerd != nil {
		in, out := &in.Containerd, &out.Containerd
		*out = new(DownloadSource)
		**out = **in
	}
	if in.Runc != nil {
		in, out := &in.Runc, &out.Runc
		*out = new(DownloadSource)
		**out = **in
	}
	if in.CNI != nil {
		in, out := &in.CNI, &out.CNI
		*out = new(DownloadSource)
		**out = **in
	}
	if in.Crictl != nil {
		in, out := &in.Crictl, &out.Crictl
		*out = new(DownloadSource)
		**out = **in
	}
	if in.CoreDNS != nil {
		in, out := &in.CoreDNS, &out.CoreDNS
		*out = new(DownloadSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentDownloadsSpec.
func (in *AgentDownloadsSpec) DeepCopy() *AgentDownloadsSpec {
	if in == nil {
		return nil
	}
	out := new(AgentDownloadsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.Downloads != nil {
		in, out := &in.Downloads, &out.Downloads
		*out = new(AgentDownloadsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalDNS != nil {
		in, out := &in.LocalDNS, &out.LocalDNS
		*out = new(LocalDNSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureHostSpec) DeepCopyInto(out *AzureHostSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureHostSpec.
func (in *AzureHostSpec) DeepCopy() *AzureHostSpec {
	if in == nil {
		return nil
	}
	out := new(AzureHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BastionSSHSpec) DeepCopyInto(out *BastionSSHSpec) {
	*out = *in
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BastionSSHSpec.
func (in *BastionSSHSpec) DeepCopy() *BastionSSHSpec {
	if in == nil {
		return nil
	}
	out := new(BastionSSHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudInitSpec) DeepCopyInto(out *CloudInitSpec) {
	*out = *in
	if in.UserDataConfigMapRef != nil {
		in, out := &in.UserDataConfigMapRef, &out.UserDataConfigMapRef
		*out = new(ConfigMapKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudInitSpec.
func (in *CloudInitSpec) DeepCopy() *CloudInitSpec {
	if in == nil {
		return nil
	}
	out := new(CloudInitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeySelector) DeepCopyInto(out *ConfigMapKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeySelector.
func (in *ConfigMapKeySelector) DeepCopy() *ConfigMapKeySelector {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPLease) DeepCopyInto(out *DHCPLease) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPLease.
func (in *DHCPLease) DeepCopy() *DHCPLease {
	if in == nil {
		return nil
	}
	out := new(DHCPLease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownloadSource) DeepCopyInto(out *DownloadSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownloadSource.
func (in *DownloadSource) DeepCopy() *DownloadSource {
	if in == nil {
		return nil
	}
	out := new(DownloadSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalHostSpec) DeepCopyInto(out *ExternalHostSpec) {
	*out = *in
	if in.MachineRef != nil {
		in, out := &in.MachineRef, &out.MachineRef
		*out = new(ProviderMachineReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalHostSpec.
func (in *ExternalHostSpec) DeepCopy() *ExternalHostSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GantryComponentSpec) DeepCopyInto(out *GantryComponentSpec) {
	*out = *in
	in.SiteComponentSpec.DeepCopyInto(&out.SiteComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GantryComponentSpec.
func (in *GantryComponentSpec) DeepCopy() *GantryComponentSpec {
	if in == nil {
		return nil
	}
	out := new(GantryComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostSpec) DeepCopyInto(out *HostSpec) {
	*out = *in
	if in.Netboot != nil {
		in, out := &in.Netboot, &out.Netboot
		*out = new(PXESpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureHostSpec)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalHostSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostSpec.
func (in *HostSpec) DeepCopy() *HostSpec {
	if in == nil {
		return nil
	}
	out := new(HostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesSpec) DeepCopyInto(out *KubernetesSpec) {
	*out = *in
	if in.NodeRef != nil {
		in, out := &in.NodeRef, &out.NodeRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.NodeLabels != nil {
		in, out := &in.NodeLabels, &out.NodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RegisterWithTaints != nil {
		in, out := &in.RegisterWithTaints, &out.RegisterWithTaints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BootstrapTokenRef != nil {
		in, out := &in.BootstrapTokenRef, &out.BootstrapTokenRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesSpec.
func (in *KubernetesSpec) DeepCopy() *KubernetesSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalDNSSpec) DeepCopyInto(out *LocalDNSSpec) {
	*out = *in
	if in.CPULimitInMilliCores != nil {
		in, out := &in.CPULimitInMilliCores, &out.CPULimitInMilliCores
		*out = new(int32)
		**out = **in
	}
	if in.MemoryLimitInMB != nil {
		in, out := &in.MemoryLimitInMB, &out.MemoryLimitInMB
		*out = new(int32)
		**out = **in
	}
	if in.RequiredPlugins != nil {
		in, out := &in.RequiredPlugins, &out.RequiredPlugins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalDNSSpec.
func (in *LocalDNSSpec) DeepCopy() *LocalDNSSpec {
	if in == nil {
		return nil
	}
	out := new(LocalDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachinaComponentSpec) DeepCopyInto(out *MachinaComponentSpec) {
	*out = *in
	in.SiteComponentSpec.DeepCopyInto(&out.SiteComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachinaComponentSpec.
func (in *MachinaComponentSpec) DeepCopy() *MachinaComponentSpec {
	if in == nil {
		return nil
	}
	out := new(MachinaComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Machine) DeepCopyInto(out *Machine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Machine.
func (in *Machine) DeepCopy() *Machine {
	if in == nil {
		return nil
	}
	out := new(Machine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Machine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfiguration) DeepCopyInto(out *MachineConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfiguration.
func (in *MachineConfiguration) DeepCopy() *MachineConfiguration {
	if in == nil {
		return nil
	}
	out := new(MachineConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationAgent) DeepCopyInto(out *MachineConfigurationAgent) {
	*out = *in
	if in.LocalDNS != nil {
		in, out := &in.LocalDNS, &out.LocalDNS
		*out = new(LocalDNSSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationAgent.
func (in *MachineConfigurationAgent) DeepCopy() *MachineConfigurationAgent {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationHostSpec) DeepCopyInto(out *MachineConfigurationHostSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationHostSpec.
func (in *MachineConfigurationHostSpec) DeepCopy() *MachineConfigurationHostSpec {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationKubernetes) DeepCopyInto(out *MachineConfigurationKubernetes) {
	*out = *in
	if in.NodeLabels != nil {
		in, out := &in.NodeLabels, &out.NodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RegisterWithTaints != nil {
		in, out := &in.RegisterWithTaints, &out.RegisterWithTaints
		*out = make([]corev1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationKubernetes.
func (in *MachineConfigurationKubernetes) DeepCopy() *MachineConfigurationKubernetes {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationKubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationList) DeepCopyInto(out *MachineConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationList.
func (in *MachineConfigurationList) DeepCopy() *MachineConfigurationList {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationRef) DeepCopyInto(out *MachineConfigurationRef) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationRef.
func (in *MachineConfigurationRef) DeepCopy() *MachineConfigurationRef {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationRefStatus) DeepCopyInto(out *MachineConfigurationRefStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationRefStatus.
func (in *MachineConfigurationRefStatus) DeepCopy() *MachineConfigurationRefStatus {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationRefStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationSpec) DeepCopyInto(out *MachineConfigurationSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
	if in.MachineSelector != nil {
		in, out := &in.MachineSelector, &out.MachineSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationSpec.
func (in *MachineConfigurationSpec) DeepCopy() *MachineConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationStatus) DeepCopyInto(out *MachineConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationStatus.
func (in *MachineConfigurationStatus) DeepCopy() *MachineConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationTemplate) DeepCopyInto(out *MachineConfigurationTemplate) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(MachineConfigurationHostSpec)
		**out = **in
	}
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(MachineConfigurationKubernetes)
		(*in).DeepCopyInto(*out)
	}
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(MachineConfigurationAgent)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationTemplate.
func (in *MachineConfigurationTemplate) DeepCopy() *MachineConfigurationTemplate {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationUpdateStrategy) DeepCopyInto(out *MachineConfigurationUpdateStrategy) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationUpdateStrategy.
func (in *MachineConfigurationUpdateStrategy) DeepCopy() *MachineConfigurationUpdateStrategy {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationUpdateStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationVersion) DeepCopyInto(out *MachineConfigurationVersion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationVersion.
func (in *MachineConfigurationVersion) DeepCopy() *MachineConfigurationVersion {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfigurationVersion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationVersionList) DeepCopyInto(out *MachineConfigurationVersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineConfigurationVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationVersionList.
func (in *MachineConfigurationVersionList) DeepCopy() *MachineConfigurationVersionList {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationVersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfigurationVersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationVersionSpec) DeepCopyInto(out *MachineConfigurationVersionSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationVersionSpec.
func (in *MachineConfigurationVersionSpec) DeepCopy() *MachineConfigurationVersionSpec {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationVersionStatus) DeepCopyInto(out *MachineConfigurationVersionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationVersionStatus.
func (in *MachineConfigurationVersionStatus) DeepCopy() *MachineConfigurationVersionStatus {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationVersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineList) DeepCopyInto(out *MachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Machine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineList.
func (in *MachineList) DeepCopy() *MachineList {
	if in == nil {
		return nil
	}
	out := new(MachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOperation) DeepCopyInto(out *MachineOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOperation.
func (in *MachineOperation) DeepCopy() *MachineOperation {
	if in == nil {
		return nil
	}
	out := new(MachineOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOperationCredential) DeepCopyInto(out *MachineOperationCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOperationCredential.
func (in *MachineOperationCredential) DeepCopy() *MachineOperationCredential {
	if in == nil {
		return nil
	}
	out := new(MachineOperationCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineOperationCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOperationCredentialAuth) DeepCopyInto(out *MachineOperationCredentialAuth) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(NamespacedSecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOperationCredentialAuth.
func (in *MachineOperationCredentialAuth) DeepCopy() *MachineOperationCredentialAuth {
	if in == nil {
		return nil
	}
	out := new(MachineOperationCredentialAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOperationCredentialList) DeepCopyInto(out *MachineOperationCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineOperationCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOperationCredentialList.
func (in *MachineOperationCredentialList) DeepCopy() *MachineOperationCredentialList {
	if in == nil {
		return nil
	}
	out := new(MachineOperationCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineOperationCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOperationCredentialSpec) DeepCopyInto(out *MachineOperationCredentialSpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOperationCredentialSpec.
func (in *MachineOperationCredentialSpec) DeepCopy() *MachineOperationCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(MachineOperationCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOperationList) DeepCopyInto(out *MachineOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOperationList.
func (in *MachineOperationList) DeepCopy() *MachineOperationList {
	if in == nil {
		return nil
	}
	out := new(MachineOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOperationSpec) DeepCopyInto(out *MachineOperationSpec) {
	*out = *in
	if in.MachineSelector != nil {
		in, out := &in.MachineSelector, &out.MachineSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOperationSpec.
func (in *MachineOperationSpec) DeepCopy() *MachineOperationSpec {
	if in == nil {
		return nil
	}
	out := new(MachineOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOperationStatus) DeepCopyInto(out *MachineOperationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]MachineOperationTargetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOperationStatus.
func (in *MachineOperationStatus) DeepCopy() *MachineOperationStatus {
	if in == nil {
		return nil
	}
	out := new(MachineOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOperationTargetInput) DeepCopyInto(out *MachineOperationTargetInput) {
	*out = *in
	if in.ProviderRef != nil {
		in, out := &in.ProviderRef, &out.ProviderRef
		*out = new(ProviderMachineSnapshot)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOperationTargetInput.
func (in *MachineOperationTargetInput) DeepCopy() *MachineOperationTargetInput {
	if in == nil {
		return nil
	}
	out := new(MachineOperationTargetInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineOperationTargetStatus) DeepCopyInto(out *MachineOperationTargetStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(MachineOperationTargetInput)
		(*in).DeepCopyInto(*out)
	}
	if in.LastAttemptAt != nil {
		in, out := &in.LastAttemptAt, &out.LastAttemptAt
		*out = (*in).DeepCopy()
	}
	if in.ProviderOperation != nil {
		in, out := &in.ProviderOperation, &out.ProviderOperation
		*out = new(ProviderOperationStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineOperationTargetStatus.
func (in *MachineOperationTargetStatus) DeepCopy() *MachineOperationTargetStatus {
	if in == nil {
		return nil
	}
	out := new(MachineOperationTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineSpec) DeepCopyInto(out *MachineSpec) {
	*out = *in
	if in.SSH != nil {
		in, out := &in.SSH, &out.SSH
		*out = new(SSHSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PXE != nil {
		in, out := &in.PXE, &out.PXE
		*out = new(PXESpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(KubernetesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(AgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(HostSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigurationRef != nil {
		in, out := &in.ConfigurationRef, &out.ConfigurationRef
		*out = new(MachineConfigurationRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineSpec.
func (in *MachineSpec) DeepCopy() *MachineSpec {
	if in == nil {
		return nil
	}
	out := new(MachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineStatus) DeepCopyInto(out *MachineStatus) {
	*out = *in
	if in.SSH != nil {
		in, out := &in.SSH, &out.SSH
		*out = new(SSHStatus)
		**out = **in
	}
	if in.Redfish != nil {
		in, out := &in.Redfish, &out.Redfish
		*out = new(RedfishStatus)
		**out = **in
	}
	if in.TPM != nil {
		in, out := &in.TPM, &out.TPM
		*out = new(TPMStatus)
		**out = **in
	}
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(AgentStatus)
		**out = **in
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(MachineConfigurationRefStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineStatus.
func (in *MachineStatus) DeepCopy() *MachineStatus {
	if in == nil {
		return nil
	}
	out := new(MachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetalmanComponentSpec) DeepCopyInto(out *MetalmanComponentSpec) {
	*out = *in
	in.SiteComponentSpec.DeepCopyInto(&out.SiteComponentSpec)
	if in.DHCPAutoInterface != nil {
		in, out := &in.DHCPAutoInterface, &out.DHCPAutoInterface
		*out = new(bool)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetalmanComponentSpec.
func (in *MetalmanComponentSpec) DeepCopy() *MetalmanComponentSpec {
	if in == nil {
		return nil
	}
	out := new(MetalmanComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedSecretReference) DeepCopyInto(out *NamespacedSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedSecretReference.
func (in *NamespacedSecretReference) DeepCopy() *NamespacedSecretReference {
	if in == nil {
		return nil
	}
	out := new(NamespacedSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PXESpec) DeepCopyInto(out *PXESpec) {
	*out = *in
	if in.PullSecretRef != nil {
		in, out := &in.PullSecretRef, &out.PullSecretRef
		*out = new(NamespacedSecretReference)
		**out = **in
	}
	if in.NetbootPullSecretRef != nil {
		in, out := &in.NetbootPullSecretRef, &out.NetbootPullSecretRef
		*out = new(NamespacedSecretReference)
		**out = **in
	}
	if in.DHCPLeases != nil {
		in, out := &in.DHCPLeases, &out.DHCPLeases
		*out = make([]DHCPLease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Redfish != nil {
		in, out := &in.Redfish, &out.Redfish
		*out = new(RedfishSpec)
		**out = **in
	}
	if in.CloudInit != nil {
		in, out := &in.CloudInit, &out.CloudInit
		*out = new(CloudInitSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PXESpec.
func (in *PXESpec) DeepCopy() *PXESpec {
	if in == nil {
		return nil
	}
	out := new(PXESpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderMachineReference) DeepCopyInto(out *ProviderMachineReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderMachineReference.
func (in *ProviderMachineReference) DeepCopy() *ProviderMachineReference {
	if in == nil {
		return nil
	}
	out := new(ProviderMachineReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderMachineSnapshot) DeepCopyInto(out *ProviderMachineSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderMachineSnapshot.
func (in *ProviderMachineSnapshot) DeepCopy() *ProviderMachineSnapshot {
	if in == nil {
		return nil
	}
	out := new(ProviderMachineSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderOperationStatus) DeepCopyInto(out *ProviderOperationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderOperationStatus.
func (in *ProviderOperationStatus) DeepCopy() *ProviderOperationStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RacerComponentSpec) DeepCopyInto(out *RacerComponentSpec) {
	*out = *in
	in.SiteComponentSpec.DeepCopyInto(&out.SiteComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RacerComponentSpec.
func (in *RacerComponentSpec) DeepCopy() *RacerComponentSpec {
	if in == nil {
		return nil
	}
	out := new(RacerComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedfishSpec) DeepCopyInto(out *RedfishSpec) {
	*out = *in
	out.PasswordRef = in.PasswordRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedfishSpec.
func (in *RedfishSpec) DeepCopy() *RedfishSpec {
	if in == nil {
		return nil
	}
	out := new(RedfishSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedfishStatus) DeepCopyInto(out *RedfishStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedfishStatus.
func (in *RedfishStatus) DeepCopy() *RedfishStatus {
	if in == nil {
		return nil
	}
	out := new(RedfishStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHSpec) DeepCopyInto(out *SSHSpec) {
	*out = *in
	out.PrivateKeyRef = in.PrivateKeyRef
	if in.Bastion != nil {
		in, out := &in.Bastion, &out.Bastion
		*out = new(BastionSSHSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHSpec.
func (in *SSHSpec) DeepCopy() *SSHSpec {
	if in == nil {
		return nil
	}
	out := new(SSHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHStatus) DeepCopyInto(out *SSHStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHStatus.
func (in *SSHStatus) DeepCopy() *SSHStatus {
	if in == nil {
		return nil
	}
	out := new(SSHStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Site) DeepCopyInto(out *Site) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Site.
func (in *Site) DeepCopy() *Site {
	if in == nil {
		return nil
	}
	out := new(Site)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Site) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteComponentSpec) DeepCopyInto(out *SiteComponentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteComponentSpec.
func (in *SiteComponentSpec) DeepCopy() *SiteComponentSpec {
	if in == nil {
		return nil
	}
	out := new(SiteComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteComponents) DeepCopyInto(out *SiteComponents) {
	*out = *in
	if in.Machina != nil {
		in, out := &in.Machina, &out.Machina
		*out = new(MachinaComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Metalman != nil {
		in, out := &in.Metalman, &out.Metalman
		*out = new(MetalmanComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gantry != nil {
		in, out := &in.Gantry, &out.Gantry
		*out = new(GantryComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Racer != nil {
		in, out := &in.Racer, &out.Racer
		*out = new(RacerComponentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteComponents.
func (in *SiteComponents) DeepCopy() *SiteComponents {
	if in == nil {
		return nil
	}
	out := new(SiteComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteList) DeepCopyInto(out *SiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Site, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteList.
func (in *SiteList) DeepCopy() *SiteList {
	if in == nil {
		return nil
	}
	out := new(SiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteSpec) DeepCopyInto(out *SiteSpec) {
	*out = *in
	if in.NodeCidrs != nil {
		in, out := &in.NodeCidrs, &out.NodeCidrs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodCidrAssignments != nil {
		in, out := &in.PodCidrAssignments, &out.PodCidrAssignments
		*out = make([]v1alpha1.PodCidrAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManageCniPlugin != nil {
		in, out := &in.ManageCniPlugin, &out.ManageCniPlugin
		*out = new(bool)
		**out = **in
	}
	if in.NonMasqueradeCIDRs != nil {
		in, out := &in.NonMasqueradeCIDRs, &out.NonMasqueradeCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LocalCIDRs != nil {
		in, out := &in.LocalCIDRs, &out.LocalCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HealthCheckSettings != nil {
		in, out := &in.HealthCheckSettings, &out.HealthCheckSettings
		*out = new(v1alpha1.HealthCheckSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.TunnelProtocol != nil {
		in, out := &in.TunnelProtocol, &out.TunnelProtocol
		*out = new(v1alpha1.TunnelProtocol)
		**out = **in
	}
	if in.TunnelMTU != nil {
		in, out := &in.TunnelMTU, &out.TunnelMTU
		*out = new(int32)
		**out = **in
	}
	in.Components.DeepCopyInto(&out.Components)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteSpec.
func (in *SiteSpec) DeepCopy() *SiteSpec {
	if in == nil {
		return nil
	}
	out := new(SiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SiteStatus) DeepCopyInto(out *SiteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SiteStatus.
func (in *SiteStatus) DeepCopy() *SiteStatus {
	if in == nil {
		return nil
	}
	out := new(SiteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageComponentSpec) DeepCopyInto(out *StorageComponentSpec) {
	*out = *in
	in.SiteComponentSpec.DeepCopyInto(&out.SiteComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageComponentSpec.
func (in *StorageComponentSpec) DeepCopy() *StorageComponentSpec {
	if in == nil {
		return nil
	}
	out := new(StorageComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TPMStatus) DeepCopyInto(out *TPMStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPMStatus.
func (in *TPMStatus) DeepCopy() *TPMStatus {
	if in == nil {
		return nil
	}
	out := new(TPMStatus)
	in.DeepCopyInto(out)
	return out
}
